### ISSUE TITLE
Simplify adding new personalities

### ISSUE THREAD

**Issue by piranna** [EniasCailliau/GirlfriendGPT#11]
Add an auto-discover mechanism reading files from a `personalities` folder, it's not too complex to do.

**Comment by EniasCailliau** [comment]
Great idea! Do you want to open a PR to add this functionality?

**Comment by Garfers** [comment]
Write please mechanism to change personality in README file. I'm trying to change to one of listed on a site, but I don't understand how to change to them. My bot don't want to go from Sasha anywhere.
Thanks.
