### ISSUE TITLE
Syntax error at startup

### ISSUE THREAD

**Issue by Vyacheslav73195** [EniasCailliau/GirlfriendGPT#12]
File "main.py", line 16
    def show_results(response_messages: List[ChatMessage]):
                                      ^
SyntaxError: invalid syntax

**Comment by EniasCailliau** [comment]
Are you running python3? Failed to replicate this error.

**Comment by Vyacheslav73195** [comment]
Yes

**Comment by EniasCailliau** [comment]
Can you pull in the most recent changes? Your problem should be fixed :)
