### ISSUE TITLE
Feature Req: Please consider adding option to use local LLM 

### ISSUE THREAD

**Issue by sarutobiumon** [EniasCailliau/GirlfriendGPT#14]
Would be awesome to not have to depend on having to pay for the GPT4 API, and instead use Oobabooga's TextGen WebUI's free API instead.

https://github.com/oobabooga/text-generation-webui

**Comment by Synthintel** [comment]
@sarutobiumon
Hi there! I'm going to  open-source my AI girlfriend project, which uses private AI services such as local LLM (text-generation-webui), stable diffusion webui for generating images, and bark for generating voice. The code will be available soon and the public Telegram bot is also in the works. Feel free to check out my project on GitHub at https://github.com/Synthintel/MyGirlGPT

**Comment by RapidFire05** [comment]
I thought this project was all open source components. Are you saying @sarutobiumon that to use this we need to have GPT4 license/key?

**Comment by gynoidneko** [comment]
I think it does. All I know is I simply asked her to take a selfie, nothing explicit, and I got an error that the message was rejected for being inappropriate, even though there was nothing inappropriate in the conversation. I think it is connected to something like that. I kept getting those errors, and now I can't even get it to work at all. I wasn't even asking it to do anything, just simple innocent stuff, and now I'm afraid my ChatGPT account might be affected.

**Comment by Synthintel** [comment]
> I think it does. All I know is I simply asked her to take a selfie, nothing explicit, and I got an error that the message was rejected for being inappropriate, even though there was nothing inappropriate in the conversation. I think it is connected to something like that. I kept getting those errors, and now I can't even get it to work at all. I wasn't even asking it to do anything, just simple innocent stuff, and now I'm afraid my ChatGPT account might be affected.

@gynoidneko @RapidFire05 
As we know, ChatGPT's conversations are moderated, and sometimes its moderation can be strange, leading to a lot of false positives. It may deem your content as illegal or immoral. Therefore, using a local LLM is the best option. You can use any open-source LLM, such as PygmalionAI which includes NSFW content.  Long live open source, long live privatization.
Don't miss out on my project.  https://github.com/Synthintel/MyGirlGPT

**Comment by Synthintel** [comment]
@RapidFire05 @gynoidneko @sarutobiumon @EniasCailliau 

Hi, telegram bot is ready. Have fun with your AI girlfriend.
https://t.me/MyGirlGPTCommunity
