### ISSUE TITLE
How to run in Telegram

### ISSUE THREAD

**Issue by KirMozor** [EniasCailliau/GirlfriendGPT#15]
I can't figure out how to run it in the Telegram bot?
Locally I was able to, but how on Telegram?
Can you give me a detailed instruction

**Comment by Justieku** [comment]
I cannot even able to run it localy...

**Comment by Justieku** [comment]
> 

It's ok, steamship is working. Now, i have a telegram token, what is the next step?

**Comment by Justieku** [comment]
> > 
> 
> It's ok, steamship is working. Now, i have a telegram token, what is the next step?

There is no lib to work with telegram. Possibly, Enias Cailliau don't make telegram chat support yet.

steamship_langchain==0.0.21rc0
pytimeparse
termcolor
steamship==2.16.10rc6
langchain==0.0.168

**Comment by shz0d** [comment]
@EniasCailliau I created a person and a file, but after deploying and running the Telegram bot, the person's name did not change. When I asked the bot about the AI's name, it said "Sacha."

**Comment by Justieku** [comment]
> Just updated the deploy instructions.
> 
> <img alt="image" width="1045" src="https://user-images.githubusercontent.com/13366849/242220855-730f2a5c-f762-4153-8d9c-a7f271ea9aa8.png">
> Let me know if that works for you 🙏

After new changes there are new errors and issues as well.

**Comment by EniasCailliau** [comment]
Fixed in most recent commit 🎉
