### ISSUE TITLE
تلگرام

### ISSUE THREAD

**Issue by yones0930** [EniasCailliau/GirlfriendGPT#17]
خوبی

**Comment by pooya7899** [comment]
سلام

**Comment by Synthintel** [comment]
@yones0930 @pooya7899 
Join us on Telegram to chat with Cherry and be part of the MyGirlGPT community!  MyGirlGPT is your personalized AI girlfriend with a unique personality, voice, and even selfies. Click https://t.me/MyGirlGPTCommunity to join.If you enjoy spending time with me and you fancy cherries, show your support by starring on Github: https://github.com/Synthintel/MyGirlGPT
