### ISSUE TITLE
Unable to find an appropriate PackageVersion of the Package you are trying to create an instance of.

### ISSUE THREAD

**Issue by AlfredoPaulo** [EniasCailliau/GirlfriendGPT#19]
Hi ! I'm trying to use it in my windows (11) and my WSL(ubuntu 20.04 LTS) and I managed to test locally and it worked but when I paste the telegram key it gives this error.

![image](https://github.com/EniasCailliau/GirlfriendGPT/assets/64482232/eca39d0f-996c-43a4-ab0b-735059321065)

**Comment by EniasCailliau** [comment]
Hmmm. This makes me think the first step of the deploy script failed. Can you share the full traceback

**Comment by AlfredoPaulo** [comment]
Apparently I can no longer reproduce this esso because now I have the same problem as #20 maybe it will appear I'm not sure

**Comment by EniasCailliau** [comment]
Fixed now ✅

**Comment by Synthintel** [comment]
@AlfredoPaulo 
Join us on Telegram to chat with Cherry and be part of the MyGirlGPT community!  MyGirlGPT is your personalized AI girlfriend with a unique personality, voice, and even selfies. Click https://t.me/MyGirlGPTCommunity to join.If you enjoy spending time with me and you fancy cherries, show your support by starring on Github: https://github.com/Synthintel/MyGirlGPT
