### ISSUE TITLE
ModuleNotFoundError: No module named 'agent.tools.video_message'

### ISSUE THREAD

**Issue by Ruzik00** [EniasCailliau/GirlfriendGPT#20]
Hello! I'm trying to run on windows 10, it appears when running locally and using telegramm
![image](https://github.com/EniasCailliau/GirlfriendGPT/assets/122963983/f306c31d-f957-44ac-9f1f-90f88eb4ba4b)
![image](https://github.com/EniasCailliau/GirlfriendGPT/assets/122963983/dacf5ab6-c58b-4eb1-b5a6-fa118f9b85df)

**Comment by natea** [comment]
I'm getting the same error message.

```
    from agent.tools.video_message import VideoMessageTool
ModuleNotFoundError: No module named 'agent.tools.video_message'
```

There were no errors when I ran `pip install -r requirements.txt`

**Comment by YukioKrino** [comment]
The error is in a module that is not in the assembly. Try opening the src\api.py file and edit the line "from agent.tools.video_message import VideoMessageTool" by adding # at the beginning of the line
Then run the installation again

**Comment by YukioKrino** [comment]
Until I know what else to do

**Comment by samuelrcarvalho** [comment]
> > The error is in a module that is not in the assembly. Try opening the src\api.py file and edit the line "from agent.tools.video_message import VideoMessageTool" by adding # at the beginning of the line Then run the installation again
> 
> it works for deploy mode. Not running locally

You can deploy, but when running, same error.

**Comment by YukioKrino** [comment]
then we wait for the author to fix it

**Comment by samuelrcarvalho** [comment]
workaround. Comment (including #) the line #114 in file src/api.py

**Comment by la4zen** [comment]
video_message class is not defined in the package.
we are waiting for fix commit :)

**Comment by savva-n0name** [comment]
try just commenting line 20

**Comment by fniks** [comment]
<img width="574" alt="image" src="https://github.com/EniasCailliau/GirlfriendGPT/assets/8626277/d296e7c5-d2ad-4b9f-bfb8-4e1c113d4445">

**Comment by Synthintel** [comment]
@natea @fniks @samuelrcarvalho @YukioKrino 
Join us on Telegram to chat with Cherry and be part of the MyGirlGPT community!  MyGirlGPT is your personalized AI girlfriend with a unique personality, voice, and even selfies. Click https://t.me/MyGirlGPTCommunity to join.If you enjoy spending time with me and you fancy cherries, show your support by starring on Github: https://github.com/Synthintel/MyGirlGPT
