### ISSUE TITLE
Question : how to stop showing selfi images

### ISSUE THREAD

**Issue by SmartKoki** [EniasCailliau/GirlfriendGPT#23]
i want ai to stop showing their selfies.
How do i do that? (sorry im not programmer)

**Comment by EniasCailliau** [comment]
Selfies are generated by a tool used by the agent. You can edit/remove tools in the `get_tools` function in `src/api.py`. 

If you comment out the `SelfieTool` the agent will stop generating selfies.

**Comment by SmartKoki** [comment]
Thankyou

**Comment by Synthintel** [comment]
@SmartKoki 
Join us on Telegram to chat with Cherry and be part of the MyGirlGPT community!  MyGirlGPT is your personalized AI girlfriend with a unique personality, voice, and even selfies. Click https://t.me/MyGirlGPTCommunity to join.If you enjoy spending time with me and you fancy cherries, show your support by starring on Github: https://github.com/Synthintel/MyGirlGPT
