### ISSUE TITLE
NameError: name 'VideoMessageTool' is not defined

### ISSUE THREAD

**Issue by Justieku** [EniasCailliau/GirlfriendGPT#24]
![image](https://github.com/EniasCailliau/GirlfriendGPT/assets/74873340/2b62afe2-ed23-4258-a6ea-cb31813eda20)
Due to issue #20, after editing src\api.py file, I get this error when trying to write something localy main.py.

**Comment by fniks** [comment]
<img width="574" alt="image" src="https://github.com/EniasCailliau/GirlfriendGPT/assets/8626277/4752e159-0aa7-477c-837a-bced8c70c791">

**Comment by Synthintel** [comment]
@fniks @Justieku 
Join us on Telegram to chat with Cherry and be part of the MyGirlGPT community!  MyGirlGPT is your personalized AI girlfriend with a unique personality, voice, and even selfies. Click https://t.me/MyGirlGPTCommunity to join.If you enjoy spending time with me and you fancy cherries, show your support by starring on Github: https://github.com/Synthintel/MyGirlGPT
