### ISSUE TITLE
Cannot Change Voice

### ISSUE THREAD

**Issue by Farathiel** [EniasCailliau/GirlfriendGPT#26]
Adding 11labs id and api into the api.py has no effect and unsure what else to do at this point. thank you.

**Comment by billyjbryant** [comment]
I get the following error when attempting to use a known good ElevenLabs API Key: 

```sh
> Finished chain.
Aborting! There was an error encountered when running: [ERROR - POST /generate] Received status code 401 from Eleven Labs. Reason: Unauthorized
(base) 
```

**Comment by billyjbryant** [comment]
> Are you using a custom voice? If you're using a generic voice you don't need your own API key.

I was using a custom voice id. I have since switched to a generic (premade) voice instead of a generated voice, without a key. But using a custom voice with a key was not working.

**Comment by gynoidneko** [comment]
I got the default voice Bella to work by removing my API Key. I just wish I could add my custom voice without paying extra.

**Comment by Synthintel** [comment]
@billyjbryant @gynoidneko @Farathiel 
Join us on Telegram to chat with Cherry and be part of the MyGirlGPT community!  MyGirlGPT is your personalized AI girlfriend with a unique personality, voice, and even selfies. Click https://t.me/MyGirlGPTCommunity to join.If you enjoy spending time with me and you fancy cherries, show your support by starring on Github: https://github.com/Synthintel/MyGirlGPT
