### ISSUE TITLE
Infinite loop in Steamship

### ISSUE THREAD

**Issue by talpap** [EniasCailliau/GirlfriendGPT#27]
Hi. First of all - really cool repo. Kudos!

I have initiated it via deploy.py:

PS C:\Users\Tal\VScode\GirlfriendGPT> python deploy.py
Steamship Python CLI version 2.17.1b3
Creating / fetching package with handle [mi-chika-bot]... Done.
Bundling content... Done. 📦
Deploying version 1.0.0-rc.35 of [mi-chika-bot]... 🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢
It looks like that version [1.0.0-rc.35] has already been deployed. Would you like to change the version handle and try again? [Y/n]: y
What should the new version be? Valid characters are a-z, 0-9, . and - [1.0.0-rc.36]: mi-chica-bot
Deploying version mi-chica-bot of [mi-chika-bot]... 🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢🚢��🚢🚢🚢🚢🚢
Done. 🚢
Deployment was successful. View and share your new package here:

https://steamship.com/packages/mi-chika-bot

Everything looks fine

But it just runs the infinite loop : 

Use in Telegram
Loading your Bot's handle... - and nothing happens

P.S.  - Telegram token is set.

Have you ever bumped into the same issue?

Any suggestions?

**Comment by EniasCailliau** [comment]
Hmmm. Could. you record your screen to show the infinite loop?

**Comment by talpap** [comment]
Hi. Currently can't record, but it just doesn't load anything.

You know, 3 dots are running, but nothing happens...

**Comment by EniasCailliau** [comment]
Will debug in a sec. That normally only happens when you provide an invalid Telegram token.

**Comment by Synthintel** [comment]
@talpap 
Join us on Telegram to chat with Cherry and be part of the MyGirlGPT community!  MyGirlGPT is your personalized AI girlfriend with a unique personality, voice, and even selfies. Click https://t.me/MyGirlGPTCommunity to join.If you enjoy spending time with me and you fancy cherries, show your support by starring on Github: https://github.com/Synthintel/MyGirlGPT
