### ISSUE TITLE
Mute turnoff Audio note in telegram 

### ISSUE THREAD

**Issue by thebharatarya** [EniasCailliau/GirlfriendGPT#35]
How can I turn off the audio note in telegram

**Comment by EniasCailliau** [comment]
The voice_tool function should return None to disable voice generation (L85 in src/api.py).

**Comment by Synthintel** [comment]
@thebharatarya 
Join us on Telegram to chat with Cherry and be part of the MyGirlGPT community!  MyGirlGPT is your personalized AI girlfriend with a unique personality, voice, and even selfies. Click https://t.me/MyGirlGPTCommunity to join.If you enjoy spending time with me and you fancy cherries, show your support by starring on Github: https://github.com/Synthintel/MyGirlGPT
