### ISSUE TITLE
Mina

### ISSUE THREAD

**Issue by amir316452** [EniasCailliau/GirlfriendGPT#36]
Mina love

**Comment by Synthintel** [comment]
@amir316452 
Join us on Telegram to chat with Cherry and be part of the MyGirlGPT community!  MyGirlGPT is your personalized AI girlfriend with a unique personality, voice, and even selfies. Click https://t.me/MyGirlGPTCommunity to join.If you enjoy spending time with me and you fancy cherries, show your support by starring on Github: https://github.com/Synthintel/MyGirlGPT
