### ISSUE TITLE
Import Error "No module named 'agent.base'; 'agent' is not a package" 

### ISSUE THREAD

**Issue by Joemolnos** [EniasCailliau/GirlfriendGPT#37]
I try to run it locally after installing -"requirements.txt" but I get an error that says 'agent' is not a package. 
How can i resolve this?

**Comment by NetroScript** [comment]
The author of this repository broke this in https://github.com/EniasCailliau/GirlfriendGPT/commit/c84939420876357b0271bbf5452b9c8cc495af77 by adding the `from agent.base import ChatMessage` import before adding the necessary path to the environment for it.

In the `main.py` move the line 6 `sys.path.insert(0, "src")` in front of the line 4 `from agent.base import ChatMessage`.

<details>
<summary>The beginning of your file should then look like this</summary>

```python
import os
import sys

sys.path.insert(0, "src")
from agent.base import ChatMessage

```

</details>

**Comment by EniasCailliau** [comment]
Thanks for the fix @NetroScript! 

Just pushed a fix to main 🚀

**Comment by Synthintel** [comment]
@NetroScript @Joemolnos 
Join us on Telegram to chat with Cherry and be part of the MyGirlGPT community!  MyGirlGPT is your personalized AI girlfriend with a unique personality, voice, and even selfies. Click https://t.me/MyGirlGPTCommunity to join.If you enjoy spending time with me and you fancy cherries, show your support by starring on Github: https://github.com/Synthintel/MyGirlGPT
