### ISSUE TITLE
problem with connecting to telegram

### ISSUE THREAD

**Issue by PrimusC26** [EniasCailliau/GirlfriendGPT#40]
I correctly installed it locally. Then tried to connect it to telegram.

"pip install steamship" thing worked normally
but "ship deploy && ship use" says, "It looks like that handle [sacha-gpt-bot] is already in use. Would you like to change the handle and try again? [Y/n]", I clicked Y, then wrote luna-gpt-bot, but it again said "It looks like that handle [luna-gpt-bot] is already in use. Would you like to change the handle and try again? [Y/n]"
How to deal with this?

**Comment by SmartKoki** [comment]
after deploy, how should i do to connect telegram?

**Comment by EniasCailliau** [comment]
I've updated the deployment instructions to help you!

**Comment by Synthintel** [comment]
@SmartKoki @PrimusC26 
Join us on Telegram to chat with Cherry and be part of the MyGirlGPT community!  MyGirlGPT is your personalized AI girlfriend with a unique personality, voice, and even selfies. Click https://t.me/MyGirlGPTCommunity to join.If you enjoy spending time with me and you fancy cherries, show your support by starring on Github: https://github.com/Synthintel/MyGirlGPT
