### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lijnati** [EniasCailliau/GirlfriendGPT#43]
Showing this error while chatting:-
An error happened while creating a response: [ObjectNotFound]
Unable to find object id=9F829562-EE17-4B22-9BC7-9A37FCBF76C6 handle=?

**Comment by EniasCailliau** [comment]
You're running against the limits of the LLM. 

Sometimes the LLMs will hallucinate objects with UUIDs. You can ignore these and run another prompt.

**Comment by Synthintel** [comment]
@lijnati 
Join us on Telegram to chat with Cherry and be part of the MyGirlGPT community!  MyGirlGPT is your personalized AI girlfriend with a unique personality, voice, and even selfies. Click https://t.me/MyGirlGPTCommunity to join.If you enjoy spending time with me and you fancy cherries, show your support by starring on Github: https://github.com/Synthintel/MyGirlGPT
