### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by curious-rishabh** [EniasCailliau/GirlfriendGPT#45]
Can you make a video on how to generate telegram key and What string parameter has put in personality on steamship. I'm getting error while creating instance

**Comment by EniasCailliau** [comment]
Here's a guide to create a Telegram Token: https://github.com/EniasCailliau/GirlfriendGPT/blob/main/docs/register-telegram-bot.md 

Hope it helps!

**Comment by Synthintel** [comment]
@curious-rishabh 
Join us on Telegram to chat with Cherry and be part of the MyGirlGPT community!  MyGirlGPT is your personalized AI girlfriend with a unique personality, voice, and even selfies. Click https://t.me/MyGirlGPTCommunity to join.If you enjoy spending time with me and you fancy cherries, show your support by starring on Github: https://github.com/Synthintel/MyGirlGPT
