### ISSUE TITLE
not a real issue

### ISSUE THREAD

**Issue by sirsquall** [EniasCailliau/GirlfriendGPT#5]
Hi,

I added a new personnality, and try to run it locally, with steamship, but I don't know how to make it work, each time I have errors:
https://www.steamship.com/workspaces/girlfriend-ai-aabe05d4-facd-11ed-8cae-a680d79b4ceb/packages/angele-1-0-0-rc-21/manage/api

Could you please update the documentation, with maybe a step by step to get the first answer?
Also when you run the deploy.py we are prompted with few question, i'm not sure what I have to put there, for example the bot_token?

Thanks

**Comment by EniasCailliau** [comment]
Hey! Thanks for adding a ticket. I just updated the readme and deploy.py script to help you deploy faster. 

Let me know if that helps you to close the loop.

**Comment by sirsquall** [comment]
thanks, it's working like a charm
