### ISSUE TITLE
cant change the voice

### ISSUE THREAD

**Issue by SmartKoki** [EniasCailliau/GirlfriendGPT#50]
even if i change the code of speech.py , never changed

**Comment by EniasCailliau** [comment]
Can you share your code?

**Comment by Synthintel** [comment]
@SmartKoki 
Join us on Telegram to chat with Cherry and be part of the MyGirlGPT community!  MyGirlGPT is your personalized AI girlfriend with a unique personality, voice, and even selfies. Click https://t.me/MyGirlGPTCommunity to join.If you enjoy spending time with me and you fancy cherries, show your support by starring on Github: https://github.com/Synthintel/MyGirlGPT
