### ISSUE TITLE
getting InvalidParameterValueException when trying to deploy

### ISSUE THREAD

**Issue by ChenMorSays** [EniasCailliau/GirlfriendGPT#74]
When running the command `ship deploy && ship use` I'm getting:

Unable to deploy package version.
Server returned message: Unable to deploy app. Is the content valid? InvalidParameterValueException: Unzipped size must be smaller than 262144000 bytes

Any ideas?

**Comment by gapizaver** [comment]
If using the latest version, check the [README.md](https://github.com/EniasCailliau/GirlfriendGPT#getting-started) file again. The commands to run/deploy the companion have been updated.

**Comment by ChenMorSays** [comment]
It works thanks!

**Comment by gapizaver** [comment]
In that case you can [close the issue](https://docs.github.com/en/enterprise-cloud@latest/issues/tracking-your-work-with-issues/closing-an-issue) 🙂
